{{- range $vs:= $.Values.virtualservice }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  lables:
    environment: {{ $vs.environment }}
  name: {{ $vs.vsName }}
  namespace: {{ $vs.namespace }}
spec:
  exportTo:
    - '.'
    - istio-internal
  hosts:
    - {{ $vs.servers.host_url }}
  gateways:
    - {{ vs.gatewayName }}
  http:
    - route:
        - destination:
            host: {{ $vs.service.name }}
            port:
              number: {{ $vs.service.portNumber }}
---
{{- end }}