apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: editor-binding
subjects:
- kind: ServiceAccount
  name: editor
  namespace: tst
roleRef:
  kind: Role
  name: editor
  apiGroup: rbac.authorization.k8s.io
