apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: viewer
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps", "extensions", "batch", "autoscaling", "networking.k8s.io", "rbac.authorization.k8s.io", "policy", "storage.k8s.io", "apiextensions.k8s.io"]
  resources: ["*"]
  verbs: ["get", "watch", "list"]
