apiVersion: v1
kind: ServiceAccount
metadata:
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ .Values.namespace }}
annotations:
    iam.gke.io/gcp-service-account: {{ .Values.serviceAccount.annotation }}