apiVersion: apps/v1
kind: Deployment
metadata:
  name: page_kishalay_deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: page-kishalay
  template:
    metadata:
      labels:
        app: page-kishalay
    spec:
      containers:
      - name: new-app-container-1
        image: kishalayb18/page_kishalay:v1
        ports:
        - containerPort: 80
        imagePullPolicy: Always