{{- define "common.serviceAccount" -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
{{- if .Values.serviceAccount.name -}}
    name: {{ .Values.serviceAccount.name }}
{{- end -}}
{{- if .Values.serviceAccount.gcpServiceAccount -}}
    annotations:
        iam.gke.io/gcp-service-account: {{ .Values.serviceAccount.gcpServiceAccount}}
{{- end -}}
{{- end -}}