apiVersion: batch/v1
kind: Job
metadata:
  name: vault-fetch-credentials
spec:
  template:
    spec:
      containers:
      - name: vault
        image: vault:latest
        command: ["sh", "-c", "vault kv get -format=json secret/mysql > /vault/secrets/mysql.json"]
        env:
        - name: VAULT_ADDR
          value: "http://vault:8200"
        - name: VAULT_TOKEN
          value: "<Root Token>"
        volumeMounts:
        - name: vault-secrets
          mountPath: /vault/secrets
      restartPolicy: Never
      volumes:
      - name: vault-secrets
        emptyDir: {}
