apiVersion: v1
kind: Pod
metadata:
  name: first-pod
  labels:
    app: MyApp
spec:
  containers:
    - name: sample-container-1
      image: nginx:v2
      imagePullPolicy: Always
      resources:
        requests:
          memory: 1Mi
        limits:
          memory: 200Mi