apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-deployment
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: new-app-container-1
        image: nginx
        ports:
        - containerPort: 80
        imagePullPolicy: Always