pipeline {
    agent any
    parameters {
        string (name: 'namespace', defaultValue: 'skill', description: 'namespace name variable')
        string (name: 'cluster', defaultValue: 'minikube', description: 'cluster name variable')
    }
    stages {
        stage ("git clone"){
            steps{
                git url: "https://github.com/kishalayb18/DevOps.git", branch: "main"
                echo 'code cloning completed'
            }
        }
        
        stage ("deploy to kubernetes") {
            steps {
                // dir will route to the right folder in the cloned repository
                echo "cluster: ${cluster} namespace: ${namespace}"
                dir('k8s-deployment/single-container-application') {
                    script {
                        kubernetesDeploy (configs: 'namespace.yaml, deployment.yaml, service.yaml',  kubeconfigId: 'kubernetes_config')
                    }
                }
            }
        }
    }
}