apiVersion: v1
kind: Service
metadata: 
  name: sample-static-service
  namespace: sample
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 80
      nodePort: 31012
  selector:
    app: sample-app