apiVersion: v1
kind: Namespace
metadata:
  name: wrk
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota-sample
  namespace: wrk
spec:
  hard:
    pods: "10"
    requests.cpu: "500m"
    requests.memory: "500Mi"
    limits.cpu: "1Gi"
    limits.memory: "1Gi"