apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sit-pvc
  namespace: wrk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard