
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
          - name:  sample-secretvolume
            mountPath:  /temp
          - name: sample-secretvolume
            mountPath: /temp2/newpath
      volumes:
        - name:  sample-secretvolume
          secret:
            secretName:  sample-secret
