apiVersion: v1
kind: PersistentVolume
metadata:
  name: hy-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: disk-demo
    fsType: ext4  
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard