apiVersion: v1/apps
kind: Deployment
metadata:
  name: deployment_cm
  labels:
    app: sample_cm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample_cm
  template:
    metadata:
      labels:
        app: sample_cm
    spec:
      caontainers:
      - name: sample_nginx_cm
        image: nginx
        volumeMounts:
          name: db-connection
          mountPath: /opt
        ports:
        - containerPort: 8091

    volumes:
      - name: db-connection
        configMap:
          name: dbConfig