apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongosecond
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - image: mongo:4.4
          name: mongosecond
          args: ["--dbpath", "/data/db"]
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "admin"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "password"
          volumeMounts:
            - name:  mongosecond-volume
              mountPath:  /data/db
      volumes:
        - name: mongosecond-volume
          emptyDir: {}