apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidecar-deployment
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: webapplication
  template:
    metadata:
      labels:
        app: webapplication
    spec:
      containers:
      - name: webapplication                 
        image: nginx
        volumeMounts:
        - mountPath: /nginx-mount     
          name: cache-volume
      - name: sidecar                   
        image: redis
        volumeMounts:
        - mountPath: /cache-mount    
          name: cache-volume
      volumes:
        - name: cache-volume
          emptyDir: {}