apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    app: MyApp
    env: blue
spec:
  containers:
  - name: sample
    image: kishalaypage:v1
    ports:
    - containerPort: 8080
    imagePullPolicy: Never
